name: healthapp
description: A health mobile app MVP

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  flutter_local_notifications: 12.0.4
  file_picker: ^6.1.1
  path_provider: ^2.1.2
  image_picker: ^1.0.7
  table_calendar: ^3.0.9
  timezone: ^0.9.2
  google_sign_in: ^6.2.1
  intl: ^0.18.1
  firebase_core: ^2.25.4
  cloud_firestore: ^4.13.5
  firebase_auth: ^4.17.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  plugin:
    platforms:
      linux:
        default_package: none
      macos:
        default_package: none
      windows:
        default_package: none
      android:
        package: com.example.healthapp
        pluginClass: HealthAppPlugin
